package com.nastation.c10;

/**
 * the exception in the following program is not caught in main( )
 * 
 * @author Kris
 * 
 */
public class ThrowOut {
	public static void main(String[] args) throws Throwable {
		try {
			throw new Throwable();
		} catch (Throwable e) {
			System.err.println("Caught in main()");
		}
	}
}